### ISSUE TITLE
Send real error message

### ISSUE THREAD

**Issue by olegabr** [Somewater/TelegramAlarmCallback#3]
Now for any message I have something like this `my_stream_name received messages matching <level:"6"> (Current grace time: 3 minutes)` in my telegram.

It would be more helpful to send the whole message. e.g. the first message caused the alert trigger.

I can do it myself if the issue #2 would be resolved.

Thanks.

**Comment by olegabr** [comment]
did it. commit in my master. see in PR #1

**Comment by igroykt** [comment]
@olegabr класс. Good job :)
